name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.0'
      - name: Installer pakker
        run: |
          cd wombokombo
          pip install flask pymysql pytest werkzeug
      - name: Kjør tester
        run: |
          cd wombokombo
          pytest test_app.py

    